SupportApp/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from dashboard.views import DashboardView, TitleView
from django.shortcuts import render

urlpatterns = [
    path('', TitleView.as_view(), name='dashboard'),
    path('dashboard/', include('dashboard.urls')),
    path('support/', include('support.urls')),
    path('mail/', include('mail.urls')),
    path('accounts/', include('accounts.urls')),
    path('aptitude/', include('aptitude.urls')),
    path('information/', include('information.urls')),
    path('jobdocs/', include('jobdocs.urls')),
    path('todo/', include('todo.urls')),
    path('social-auth/', include('allauth.urls')),
    path("admin/", admin.site.urls),
    # path("test/error/", lambda request: render(request, 'generation_error.html'))
]

dashboard/urls.py
from django.urls import path
from .views import DashboardView, EventListAPI, EventCreateAPI, EventUpdateAPI, EventDeleteAPI

app_name = 'dashboard'
urlpatterns = [ 
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('api/events/', EventListAPI.as_view(), name='event_list_api'),
    path('api/events/create/', EventCreateAPI.as_view(), name='event_create_api'),
    path('api/events/update/<int:pk>/', EventUpdateAPI.as_view(), name='event_update_api'),
    path('api/events/delete/<int:pk>/', EventDeleteAPI.as_view(), name='event_delete_api'),
]

information/urls.py
from django.urls import path
from .views import (
    InformationView, 
    InformationDetailView, 
    InformationAddView, 
    AddCustomFieldView, 
    CompanyDeleteView,
    CustomFieldDeleteView,
    InlineUpdateView,
    UpdateStepSelectionView,
    UpdateCurrentStepView,
    ResetCurrentStepView,
)

app_name = 'information'
urlpatterns = [ 
    path('information_list/', InformationView.as_view(), name='company_information_list'),
    path('information_add/', InformationAddView.as_view(), name='company_information_add'),
    path('information_detail/<int:pk>/', InformationDetailView.as_view(), name='company_information_detail'),
    path('add_custom_field/', AddCustomFieldView.as_view(), name='add_custom_field'),
    path('information_delete/<int:company_id>/', CompanyDeleteView.as_view(), name='company_information_delete'),
    path('custom_field_delete/', CustomFieldDeleteView.as_view(), name='custom_field_delete'),
    path('inline_update/', InlineUpdateView.as_view(), name='inline_update'),
    path('update_step_selection/', UpdateStepSelectionView.as_view(), name='update_step_selection'),
    path('update_current_step/', UpdateCurrentStepView.as_view(), name='update_current_step'),
    path('reset_current_step/', ResetCurrentStepView.as_view(), name='reset_current_step'),
]

mail/urls.py
from django.urls import path
from .views import EmailCreate, EmailReplyCreate, EmailStructureCheck, EmailTemplate

app_name = 'mail'
urlpatterns = [
    path('mail_create/', EmailCreate.as_view(), name='mail_create'),  
    path('mail_reply_create/', EmailReplyCreate.as_view(), name='mail_reply_create'), 
    path('mail_structure_check/', EmailStructureCheck.as_view(), name='mail_structure_check'),
    path('mail_template/', EmailTemplate.as_view(), name='mail_template'),  
]

information/models.py
from django.db import models
from accounts.models import CustomUser

class Company(models.Model):
    """会社情報モデル"""
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="companies", verbose_name="ユーザー")
    name = models.CharField(max_length=200, verbose_name="会社名")
    ceo = models.CharField(max_length=200, verbose_name="取締役代表")
    address = models.CharField(max_length=300, verbose_name="本社所在地")
    established_year = models.CharField(max_length=100, verbose_name="設立年度")
    capital = models.CharField(max_length=100, verbose_name="資本金")
    employees_count = models.CharField(max_length=100, verbose_name="従業員数")
    business_content = models.TextField(max_length=600, verbose_name="事業内容")
    official_website = models.URLField(max_length=200, verbose_name="公式HP")
    

    def __str__(self):
        return self.name


class CustomField(models.Model):
    """会社情報のカスタムフィールドモデル"""
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name="custom_fields")
    field_name = models.CharField(max_length=100, verbose_name="項目名")
    field_value = models.CharField(max_length=255, verbose_name="値")

    def __str__(self):
        return f"{self.field_name}: {self.field_value}"

class Step(models.Model):
    """選考ステップモデル"""
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    order = models.PositiveIntegerField()

    # ソート
    class Meta:
        ordering = ['order']

    def __str__(self):
        return self.name

class Progress(models.Model):
    """進捗モデル"""
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    current_step = models.ForeignKey(Step, on_delete=models.SET_NULL, null=True, blank=True, related_name='current_for')
    selected_steps = models.ManyToManyField(Step, related_name='selected_for')

    def __str__(self):
        return f"{self.user} - {self.company.name} - Progress"

    # 選択中のステップを取得
    def get_ordered_selected_steps(self):
        return self.selected_steps.all().order_by('order')

    # 完了済みのステップを取得
    def get_completed_steps(self):
        if self.current_step:
            return self.get_ordered_selected_steps().filter(order__lt=self.current_step.order)
        return self.get_ordered_selected_steps().none()

information/views.py
from django.views.generic import TemplateView,View, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse
from .models import Company, CustomField, Step, Progress
from dashboard.models import Event


class InformationView(LoginRequiredMixin, TemplateView):
    """会社情報ページ"""

    template_name = 'information/company_information_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            context['companies'] = Company.objects.filter(user=self.request.user).order_by('-id')
        except Company.DoesNotExist:
            context['companies'] = None
        return context


class InformationDetailView(LoginRequiredMixin, DetailView):
    """会社情報詳細ページ"""
    
    model = Company
    context_object_name = 'company'
    template_name = 'information/company_information_detail.html'

    def get_queryset(self):
        """ログインユーザーに紐づくCompanyのみ取得可能"""
        return Company.objects.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        company = self.object  # DetailViewが自動で取得してくれたCompany
        context['custom_fields'] = CustomField.objects.filter(company=company)

        # 選考ステップの進捗情報を取得
        progress, created = Progress.objects.get_or_create(user=self.request.user, company=company)

        if created:
            # 初期状態：デフォルトの選択ステップ（固定値 order=1,2,3,4,5）
            default_steps = Step.objects.filter(order__in=[1, 2, 3, 4, 5])
            progress.selected_steps.set(default_steps)

            # current_stepは常にorderが最小のステップから始める
            if default_steps.exists():
                progress.current_step = default_steps.order_by('order').first()
            else:
                progress.current_step = None
            progress.save()

        # 進捗情報を取得
        all_steps = Step.objects.all().order_by('order')
        selected_steps = progress.get_ordered_selected_steps()
        completed_steps = progress.get_completed_steps()
        current_step = progress.current_step
        current_step_index = list(selected_steps).index(current_step) if current_step else 0

        context['progress'] = progress
        context['all_steps'] = all_steps
        context['current_step'] = current_step
        context['selected_steps'] = selected_steps
        context['completed_steps'] = completed_steps
        context['current_step_index'] = current_step_index

        # イベント情報を取得
        events = Event.objects.filter(company=company, user=self.request.user).order_by('start')
        context['events'] = events
        
        return context


class InformationAddView(LoginRequiredMixin, View):
    """会社情報追加ページ"""

    def post(self, request):
        name = request.POST.get('name', '')
        company = Company.objects.create(
            user=request.user,
            name=name,
        )
        return redirect('information:company_information_list')


@method_decorator(csrf_exempt, name='dispatch')
class AddCustomFieldView(LoginRequiredMixin, View):
    """カスタムフィールド追加API"""

    def post(self, request):
        try:
            field_name = request.POST.get('field_name', '')
            field_value = request.POST.get('field_value', '')
            company_id = request.POST.get('company_id', '')

            company = Company.objects.get(id=company_id, user=request.user)

            custom_field = CustomField.objects.create(
                company=company,
                field_name=field_name,
                field_value=field_value
            )
            return JsonResponse({'status': 'success', 'field_id': custom_field.id})
        except Company.DoesNotExist:
            return JsonResponse({'status': 'error', 'message': 'Company not found or permission denied'}, status=404)
        except Exception as e:
            return JsonResponse({'status': 'error', 'message': str(e)}, status=400)


@method_decorator(csrf_exempt, name='dispatch')
class CompanyDeleteView(LoginRequiredMixin, View):
    """会社情報削除API"""

    def post(self, request, company_id):
        company = get_object_or_404(Company, id=company_id, user=request.user)
        try:
            company.delete()
            return JsonResponse({'redirect_url': reverse('information:company_information_list')})
        except Exception as e:
            return JsonResponse({'error': str(e)}, status=500)


@method_decorator(csrf_exempt, name='dispatch')
class CustomFieldDeleteView(LoginRequiredMixin, View):
    """カスタムフィールド削除API"""

    def post(self, request, *args, **kwargs):
        field_id = request.POST.get("field_id")
        try:
            custom_field = CustomField.objects.get(id=field_id, company__user=request.user)
            custom_field.delete()
            return JsonResponse({'success': True})
        except CustomField.DoesNotExist:
            return JsonResponse({'success': False, 'error': '削除できませんでした。'}, status=403)


@method_decorator(csrf_exempt, name='dispatch')
class InlineUpdateView(LoginRequiredMixin, View):
    """フィールド更新API"""

    def post(self, request, *args, **kwargs):
        model_type = request.POST.get("model")
        field = request.POST.get("field")
        value = request.POST.get("value")

        # 既存フィールドの更新
        if model_type == "company":
            try:
                company = Company.objects.get(id=request.POST.get("id"), user=request.user)
                setattr(company, field, value)
                company.save()
                return JsonResponse({"success": True})
            except Company.DoesNotExist:
                return JsonResponse({"success": False, "error": "会社が見つかりません"}, status=404)

        # カスタムフィールドの更新
        elif model_type == "custom_field":
            try:
                custom_field = CustomField.objects.get(id=request.POST.get("id"), company__user=request.user)
                setattr(custom_field, field, value)
                custom_field.save()
                return JsonResponse({"success": True})
            except CustomField.DoesNotExist:
                return JsonResponse({"success": False, "error": "カスタムフィールドが見つかりません"}, status=404)

        return JsonResponse({"success": False, "error": "不正なリクエスト"}, status=400)


@method_decorator(csrf_exempt, name='dispatch')
class UpdateStepSelectionView(LoginRequiredMixin, View):
    """選考ステップの選択状態を更新するAPI"""

    def post(self, request):
        step_id = int(request.POST.get('step_id'))
        checked = request.POST.get('checked') == 'true'
        company_id = int(request.POST.get('company_id'))

        company = Company.objects.get(user=request.user, id=company_id)
        progress, _ = Progress.objects.get_or_create(user=request.user, company=company)
        step = Step.objects.get(id=step_id)

        if checked:
            progress.selected_steps.add(step)
        else:
            progress.selected_steps.remove(step)

        ordered_steps = progress.get_ordered_selected_steps()
        progress.current_step = ordered_steps.first() if ordered_steps.exists() else None

        progress.save()

        return JsonResponse({"status": "ok"})


@method_decorator(csrf_exempt, name='dispatch')
class UpdateCurrentStepView(LoginRequiredMixin, View):
    """選考ステップの現在のステップを更新するAPI"""

    def post(self, request):
        step_id = int(request.POST.get('step_id'))
        progress_id = int(request.POST.get('progress_id'))

        progress = Progress.objects.get(id=progress_id, user=request.user)
        step = Step.objects.get(id=step_id)

        if step in progress.selected_steps.all():
            progress.current_step = step
            progress.save()
            return JsonResponse({"status": "ok"})
        else:
            return JsonResponse({"status": "error", "message": "選択されていないステップです"}, status=400)
        

@method_decorator(csrf_exempt, name='dispatch')
class ResetCurrentStepView(LoginRequiredMixin, View):
    """現在のステップをリセットするAPI"""

    def post(self, request):
        progress_id = int(request.POST.get('progress_id'))

        progress = Progress.objects.get(id=progress_id, user=request.user)

        ordered_steps = progress.get_ordered_selected_steps()
        progress.current_step = ordered_steps.first() if ordered_steps.exists() else None

        progress.save()

        return JsonResponse({"status": "ok"})

templates/information/company_information_detail.html
{% extends "base/base.html" %}
{% load static %}

{% block title %}会社情報{% endblock %}
{% block information_active %}active{% endblock %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/company.css' %}">
{% endblock %}

{% block content %}
<!-- メインコンテンツ -->
<!-- 戻るボタン -->
<a type="button" class="btn btn-lg btn-link rounded-pill m-2 text-decoration-none position-absolute fs-sm-9"
  href="{% url 'information:company_information_list' %}">←戻る </a>
<!-- タイトル -->
<div>
  <h1 class="text-center mt-3">COMPANY</h1>
  <hr width="30%" class="mx-auto mt-0">
  <h6 class="text-center">会社情報</h6>
</div>
<!-- 会社情報テーブル -->
<div class="bg-light rounded h-100 p-4">
  <div class="table-responsive">
    <table class="createtable">
      <thead>
        <tr>
          <th scope="col" class="fs-sm-9">項目</th>
          <th scope="col" class="fs-sm-9">情報</th>
          <th scope="col" class="text-end"><a href="#" id="openModal"><i
                class="bi bi-plus-square-fill fs-5 p-1"></i></a></th>
        </tr>
      </thead>
      <tbody id="company-info-body">
        <tr>
          <th class="fs-sm-9">会社名</th>
          <td class="fs-sm-9" data-model="company" data-id="{{ company.id }}" data-field="name">{{ company.name }}</td>
          <td></td>
        </tr>
        <tr>
          <th class="fs-sm-9">取締役代表</th>
          <td class="fs-sm-9" data-model="company" data-id="{{ company.id }}" data-field="ceo">{{ company.ceo }}</td>
          <td></td>
        </tr>
        <tr>
          <th class="fs-sm-9">本社所在地</th>
          <td class="fs-sm-9" data-model="company" data-id="{{ company.id }}" data-field="address">{{ company.address }}</td>
          <td></td>
        </tr>
        <tr>
          <th class="fs-sm-9">設立年度</th>
          <td class="fs-sm-9" data-model="company" data-id="{{ company.id }}" data-field="established_year">{{ company.established_year }}</td>
          <td></td>
        </tr>
        <tr>
          <th class="fs-sm-9">資本金</th>
          <td class="fs-sm-9" data-model="company" data-id="{{ company.id }}" data-field="capital">{{ company.capital }}</td>
          <td></td>
        </tr>
        <tr>
          <th class="fs-sm-9">従業員数</th>
          <td class="fs-sm-9" data-model="company" data-id="{{ company.id }}" data-field="employees_count">{{ company.employees_count }}</td>
          <td></td>
        </tr>
        <tr>
          <th class="fs-sm-9">事業内容</th>
          <td class="fs-sm-9" data-model="company" data-id="{{ company.id }}" data-field="business_content">{{ company.business_content }}</td>
          <td></td>
        </tr>
        <tr>
          <th class="fs-sm-9">公式HP</th>
          <td class="fs-sm-9" data-model="company" data-id="{{ company.id }}" data-field="official_website" data-type="url">{{ company.official_website }}</td>
          <td></td>
        </tr>
        <!-- カスタムフィールド -->
        {% for field in custom_fields %}
        <tr class="custom-row" data-field-id="{{ field.id }}">
          <th class="fs-sm-9">{{ field.field_name }}</th>
          <td class="fs-sm-9" data-model="custom_field" data-id="{{ field.id }}" data-field="field_value">{{ field.field_value }}</td>
          <td class="text-end">
            <a class="delete-row"><i class="bi bi-x-circle-fill text-danger fs-6 p-1"></i></a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <input type="hidden" id="companyId" value="{{ company.id }}">
  </div>
  <!-- 会社進捗バー -->
  <h5 class="my-4">就職活動の進捗</h5>

  <!-- 進捗サークル -->
  <div class="container">
    <div class="progress-container">
      <div class="progress js-progress"></div>
      {% for step in selected_steps %}
      <div class="step-circle {% if step in completed_steps or step == current_step %}is-active{% endif %}" data-step-id="{{ step.id }}">
        {{ forloop.counter }}
      </div>
    {% endfor %}
    </div>

    <!-- 進捗ラベル -->
    <div class="d-flex justify-content-between">
      {% for step in selected_steps %}
      <small class="step-label">{{ step.name }}</small>
    {% endfor %}
    </div>

    <!-- 進捗ボタン -->
    <button class="step-btn" id="prev">戻る</button>
    <button class="step-btn" id="next">次へ</button>

    <!--ステップリスト-->
    <div class="dropdown">
      <button type="button" class="step-btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"
        data-bs-auto-close="outside">
        就活工程選択
      </button>
      <div class="dropdown-menu p-4">
        <div class="mb-3">
          <div class="form-check">
            {% for step in all_steps %}
              <input 
                type="checkbox" 
                class="form-check-input" 
                id="dropdownCheck{{ step.order }}" 
                data-company-id="{{ company.id }}"
                data-step-id="{{ step.id }}"
                {% if step in selected_steps %}checked{% endif %}
                {% if step in completed_steps %}data-completed="true"{% else %}data-completed="false"{% endif %}>
              <label class="form-check-label" for="dropdownCheck{{ step.order }}">
                {{ step.description }}
              </label>
              <br>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- 会社ごとのイベント -->
  <h5 class="mt-4">イベント</h6>
  {% if events %}
    <table class="table table-sm fontsmall">
      <tbody>
        <tr>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        {% for event in events %}
        <tr>
          <td class="td_vertical_align_middle">
            {{ event.start|date:"Y/m/d" }} <br>&emsp;～{{ event.end|date:"Y/m/d" }}</ul>
          </td>
          <td class="td_vertical_align_middle">
            <br>
            {% if event.all_day %}
              終日
            {% else %}
              {{ event.start|time:"H:i" }}～{{ event.end|time:"H:i" }}
            {% endif %}
          </td>
          <th class="td_vertical_align_middle"><br class="small">{{ event.title }}</th>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>イベントは登録されていません。<a href="{% url 'dashboard:dashboard' %}">こちらのカレンダーから登録</a>できます。</p>
  {% endif %}

<!-- 会社情報削除ボタン -->
<div class="text-end">
  <button id="delete-company-btn" class="btn btn-danger mt-3">
    <i class="bi bi-trash"></i> 会社情報を削除
  </button>
</div>

<!-- 項目追加モーダル -->
<div class="modal fade" id="addRowModal" tabindex="-1" aria-labelledby="addRowModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content shadow-lg rounded-4 border-0">
      <div class="modal-header text-white rounded-top-4">
        <h5 class="modal-title fw-bold text-white" id="addRowModalLabel">項目の追加</h5><button type="button"
          class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="閉じる"></button>
      </div>
      <div class="modal-body p-4">
        <div class="mb-3"><label for="itemNameInput" class="form-label">項目名</label><input type="text"
            class="form-control" id="itemNameInput" placeholder="例: 業種"></div>
        <div class="mb-3"><label for="itemValueInput" class="form-label">情報</label><input type="text"
            class="form-control" id="itemValueInput" placeholder="例: 情報処理サービス業界"></div>
        <div class="d-flex"><button class="btn btn-secondary" data-bs-dismiss="modal">キャンセル</button><button
            class="btn btn-primary ms-auto" id="addRowBtn">追加</button></div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block extra_js %}
<script src="{% static 'js/company_edit_info.js' %}"></script>
<script src="{% static 'js/company_info.js' %}"></script>
<script src="{% static 'js/step_update.js' %}"></script>
<script>
  const PROGRESS_ID = "{{ progress.id }}";
  const CURRENT_ACTIVE_INDEX = "{{ current_step_index }}";
</script>
{% endblock %}

templates/information/company_information_list.html
{% extends "base/base.html" %}
{% load static %}

{% block title %}会社情報{% endblock %}
{% block information_active %}active{% endblock %}

{% block content %}
<!-- メインコンテンツ -->
<h3>会社情報</h3>
<hr>
{% if companies %}
<!-- 説明文 -->
<p>会社情報をまとめることができます。右下のプラスボタンから追加することができます。</p>
<!-- 会社情報 -->
<div class="container-fluid">
    <div class="row g-4" id="company-list">
        {% for company in companies %}
            <div class="col-xl-4 col-md-6 col-sm-12">
                <a class="bg-light rounded d-flex align-items-center justify-content-between p-4 h-100" role="button"
                    href="{% url 'information:company_information_detail' company.id %}">
                    <i class="fa fa-building fa-3x text-primary"></i>
                    <div class="ms-3">
                        <h5 class="mb-0">{{ company.name }}</h5>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>
{% else %}
<!-- 会社情報がない場合 -->
<div class="alert alert-info alert-dismissible fade show" role="alert">
    <i class="fa fa-info-circle me-2"></i>
    会社情報がありません。右下のプラスボタンから追加することができます。
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endif %}

<!-- 追加ボタン -->
<div class="back-to-top">
    <button type="button" class="btn btn-lg btn-lg-square btn-primary m-2 open-modal" id="openModal"
        onclick="showmodal()">
        <i class="fa fa-plus"></i>
    </button>
</div>

<!-- モーダル本体 -->
<div class="modal fade" id="eventModal" tabindex="-1" aria-labelledby="eventModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content shadow-lg rounded-4 border-0">
            <div class="modal-header text-white rounded-top-4">
                <h5 class="modal-title fw-bold text-white" id="eventModalLabel">会社情報追加</h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"
                    aria-label="閉じる"></button>
            </div>
            <div class="modal-body p-4" id="eventModalBody">
                <form action="{% url 'information:company_information_add' %}" method="POST">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="companyNameInput" class="form-label">会社名</label>
                        <input type="text" class="form-control" id="companyNameInput" name="name" placeholder="会社名を入力">
                    </div>
                    <input type="submit" class="btn btn-primary" value="追加">
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block extra_js %}
<script src="{% static 'js/company_add_modal.js' %}"></script>
{% endblock %}